version: "3"
services:
  airplay:
    build: ./
    restart: unless-stopped
    environment: 
      - AIRPLAY_NAME=Docker
    devices:
      - /dev/snd
    #volumes:
    #  - ./shairport-sync.conf:/usr/local/etc/shairport-sync.conf
    #network_mode: host
    #network_mode: bridge
    # ports:
    #   - "5000:5000/tcp"
    #   - "6001-6011:6001-6011/udp"
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
        mode: host
      - target: 6001
        published: 6001
        protocol: udp
        mode: host
      - target: 6002
        published: 6002
        protocol: udp
        mode: host
      - target: 6003
        published: 6003
        protocol: udp
        mode: host
      - target: 6004
        published: 6004
        protocol: udp
        mode: host
      - target: 6005
        published: 6005
        protocol: udp
        mode: host
      - target: 6006
        published: 6006
        protocol: udp
        mode: host
      - target: 6007
        published: 6007
        protocol: udp
        mode: host
      - target: 6008
        published: 6008
        protocol: udp
        mode: host
      - target: 6009
        published: 6009
        protocol: udp
        mode: host
      - target: 6011
        published: 6011
        protocol: udp
        mode: host
